final: main1.o  printHex.o  printHexAndAscii.o
	gcc -o final main1.o printHex.o printHexAndAscii.o

main1.o: main1.c
	gcc -c main1.c

printHex.o: printHex.c
	gcc -c printHex.c

printHexAndAscii.o: printHexAndAscii.c
	gcc -c printHexAndAscii.c